theme: jekyll-theme-minimal
title: Microcredencial Universitaria en Inteligencia Artificial y Educación
description: Curso para introducirse en el mundo de IA aplicado a la educación mediante ejemplos prácticos
logo: /logo.png
